server:
  port: 666


spring:
  redis:
    database: 10
    timeout: 5000
    host: redis-rw.gcloud.spx
    port: 6379
    readhost: redis-ro.gcloud.spx
    readport: 6379
    jedis:
      pool:
        max-active: 2000
        max-idle: 2000
        min-idle: 100
  thymeleaf:
    cache: false
    prefix: src/main/resources/templates/

